# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 08:39
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='course',
            managers=[
                ('coursemng', django.db.models.manager.Manager()),
            ],
        ),
    ]
